#### Top 8 powerful function in python for data analysis

1. Group by
2. pivot_table
3. Aggregate
4. cross_tab
5. concat
6. apply
7. lambda
8. del(keyword)

In [43]:
import pandas as pd
insurance_db=pd.read_csv('Insurance.csv')
insurance_db.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

##### Group_by function

#### Pull up insurance charges based on region

In [44]:
insurance_db.groupby(by='region')["charges"].mean().round(1).sort_values(ascending=False)

region
southeast    14735.4
northeast    13406.4
northwest    12417.6
southwest    12346.9
Name: charges, dtype: float64

#### Pull up insurance charges based on region and sex

In [45]:
insurance_db.groupby(['region','sex'])["charges"].mean().round(1).sort_values()

region     sex
southwest  female    11274.4
northwest  male      12354.1
           female    12479.9
northeast  female    12953.2
southwest  male      13412.9
southeast  female    13499.7
northeast  male      13854.0
southeast  male      15879.6
Name: charges, dtype: float64

#### 2.Pivot_table function

In [51]:
pd.pivot_table(data = insurance_db,values='charges',index='region',columns='sex',aggfunc='max').round()

sex         female     male
region
northeast  58571.0  48549.0
northwest  55135.0  60021.0
southeast  63770.0  62593.0
southwest  48824.0  52591.0

#### Aggregate function

In [57]:
insurance_db.groupby(by='region')["charges"].agg(func=['min','max','sum']).round()

              min      max        sum
region
northeast  1695.0  58571.0  4343669.0
northwest  1621.0  60021.0  4035712.0
southeast  1122.0  63770.0  5363690.0
southwest  1242.0  52591.0  4012755.0

In [58]:
insurance_db

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [69]:
pd.crosstab(index=insurance_db['region'] , columns=insurance_db['smoker'],margins = True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

#### Apply function

In [70]:
insurance_db

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [77]:
def pof (x) :
    if x>20:
        return "Eligible"
    else:
        return "Not eligible"

In [78]:
insurance_db['eligibility_criteria'] = insurance_db['age'].apply(pof)
insurance_db

,age,sex,bmi,children,smoker,region,charges,eligibility_criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

In [81]:
insurance_db['eligibility_criteria_2'] = insurance_db['age'].apply(lambda x:"Eligible" if x>20 else "Not Eligible")
insurance_db

,age,sex,bmi,children,smoker,region,charges,eligibility_criteria,eligibility_criteria_2
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,Eligible
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,Eligible