## Task 1

#### 1.	Write a program to take a name and age from the user and print a greeting message.

In [16]:
name = input("Enter your name : ")
age = int(input("Enter your age : "))
print(f"Hi {name} we know your age is {age}")

Enter your name :  Virubhashayan
Enter your age :  21

Hi Virubhashayan we know your age is 21

#### 2.	Create a list of numbers and print only even numbers using a for loop.

In [17]:
numbers = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in numbers:
    if i%2 == 0:
        print(i)
print("These are the even numbers in the list")

2
4
6
8
10
12
14
These are the even numbers in the list

#### 3. Try except divided by 0

In [18]:
try:
    numerator=int(input("Enter the numerator : "))
    Denominator=int(input("Enter the Denominator : "))
    result =  numerator/ Denominator
    print(result)
except:
    print("Divide by 0 is not possible")

Enter the numerator :  12
Enter the Denominator :  0

Divide by 0 is not possible

#### 4. Count the vowels in the string

In [19]:
vowels = "AEIOUaeiou"
count = 0
user_input = input("Enter the string to count the vowels : ")
for i in user_input:
    if i in vowels:
        count = count + 1
print(f"The number of vowels in your string is {count}")

Enter the string to count the vowels :  virubha

The number of vowels in your string is 3

#### 5. Reverse the string without using built-in function

In [23]:
name = input("enter the string : ")
name[::-1]

enter the string :  virubhashayan

'nayahsahburiv'

#### 6. Create a dictionary with 5 key-pairs and print them

In [26]:
Student = {"Name":"Virubhashayan","Course":"B.TECH-IT","Age":20,"college":"VCET","Distict":"Erode"}
print(Student)

{'Name': 'Virubhashayan', 'Course': 'B.TECH-IT', 'Age': 20, 'college': 'VCET', 'Distict': 'Erode'}

#### 7. write a pandas code to load the csv file and show top 5 result

In [27]:
import pandas as pk

In [32]:
student_performance = pk.read_csv("StudentPerformance.Csv")
student_performance.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

#### 8. Create a dataframe with a pyhton dictionary

In [35]:
Student = {"Name":["Virubhashayan","aravind","chandru"],"Course":["B.TECH-IT","B.E-Civil","B.E-Ece"],"Age":[20,21,20],"college":["VCET",'vcet','vcet'],"Distict":["Erode","namakal","thirupur"]}
pk.DataFrame(Student)

            Name     Course  Age college   Distict
0  Virubhashayan  B.TECH-IT   20    VCET     Erode
1        aravind  B.E-Civil   21    vcet   namakal
2        chandru    B.E-Ece   20    vcet  thirupur

#### 9.replace all missing values in df with the column's mean

In [60]:
Student = {"Name":["Virubhashayan","aravind","chandru"],"Course":["B.TECH-IT","B.E-Civil","B.E-Ece"],"Age":[20,pk.NA,22],"college":["VCET",'vcet','vcet'],"Distict":["Erode","namakal","thirupur"]}
Student_table = pk.DataFrame(Student)
Student_table

            Name     Course   Age college   Distict
0  Virubhashayan  B.TECH-IT    20    VCET     Erode
1        aravind  B.E-Civil  <NA>    vcet   namakal
2        chandru    B.E-Ece    22    vcet  thirupur

In [57]:
Student_table

            Name     Course   Age college   Distict
0  Virubhashayan  B.TECH-IT    20    VCET     Erode
1        aravind  B.E-Civil  <NA>    vcet   namakal
2        chandru    B.E-Ece    22    vcet  thirupur

In [59]:
Student_table['Age']=Student_table['Age'].fillna(Student_table['Age'].mean())
Student_table

            Name     Course   Age college   Distict
0  Virubhashayan  B.TECH-IT  20.0    VCET     Erode
1        aravind  B.E-Civil  21.0    vcet   namakal
2        chandru    B.E-Ece  22.0    vcet  thirupur

#### 10. Filter the age where age is gratter than 30

In [71]:
employee = {"Name":["Virubhashayan","aravind","chandru","ramu","somu"] , "Age":[20,24,22,32,36]}
emp_table=pk.DataFrame(employee)
for i in emp_table['Age'] :
    if i > 30:
        print(i)
print("those members ages are more than 30 ")

32
36
those members ages are more than 30

#### The End

## Task 2 ( Advance data analysis topic )

In [52]:
import pandas as pd
sales_data_01 = pd.read_csv('Sales_transaction-2017.csv')
sales_data_02 = pd.read_csv('Sales_transaction-2018.csv')
sales_data_03 = pd.read_csv('Sales_transaction-2019.csv')

In [67]:

main_data_cleaned = pd.concat([sales_data_01, sales_data_02, sales_data_03])

In [68]:
main_data_cleaned

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [69]:
main_data_cleaned = main_sales_data[
    main_sales_data['Date'].notna() & 
    (main_sales_data['Date'].astype(str).str.strip() != '')
].copy()

In [70]:
main_columns = ['Date', 'Voucher', 'Party', 'Product', 'Qty', 'Rate']
main_data_cleaned = main_data_cleaned[main_columns]

In [71]:
def clean_numeric_values(value):
    if pd.isna(value): 
      
        return 0
    clean_val = str(value).replace(',', '').strip()
    try:
        
        return float(clean_val)
    except ValueError:
        return 0

In [72]:
main_data_cleaned ['Qty'] = main_data_cleaned ['Qty'].apply(clean_numeric_values)
main_data_cleaned ['Rate'] = main_data_cleaned ['Rate'].apply(clean_numeric_values)

In [73]:
text_cols = ['Voucher', 'Party', 'Product']
for i in text_cols:
    main_data_cleaned[i] = main_data_cleaned[i].astype(str).str.strip()

In [75]:
main_data_cleaned

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0
...,...,...,...,...,...,...
19167,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0
19168,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0

In [78]:
main_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95562 entries, 0 to 19171
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     37518 non-null  datetime64[ns]
 1   Voucher  95562 non-null  object
 2   Party    95562 non-null  object
 3   Product  95562 non-null  object
 4   Qty      95562 non-null  float64
 5   Rate     95562 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 5.1+ MB

In [77]:
main_data_cleaned['Date'] = pd.to_datetime(main_data_cleaned['Date'],errors ='coerce' )

## Task -3

In [79]:
import pandas as pd

In [80]:
college_dep = {"name":['arun','vimal','kumar','raju','vishnu'],"Dep":['It','cse','mech','it','csc']}

In [87]:
college_dep=pd.DataFrame(college_dep)

In [88]:
college_dep_fees = {"Fees":["75k",'80k','60k','75k','80k'],"Dep":['It','cse','mech','it','csc']}

In [89]:
college_dep_fees=pd.DataFrame(college_dep_fees)

In [90]:
pd.merge(college_dep,college_dep_fees,on="Dep")

     name   Dep Fees
0    arun    It  75k
1   vimal   cse  80k
2   kumar  mech  60k
3    raju    it  75k
4  vishnu   csc  80k

##### Here we merge two dataFrame with the common feature Dep

## Task -4

In [110]:
number_list = []
def list_squre(list_1):
    for i in list_1:
        number_list.append(i*i)
    return number_list

In [111]:
list_squre([1,2,3,4,5,6,7,8,9])

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [114]:
list_1 =[1,2,3,4,5,6,7,8,9]  # HERE WE USE THE LIST COMPREHENSION we use this for square the valuse inside the list
[i*i  for i in list_1]

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [115]:
# list comprehension for find even in the list

In [116]:
#without list comprehension

In [120]:
numbers = [23,4,523,678,34,52,87,98,12,32,45,67]
even =[]
for num in numbers:
    if num%2 == 0:
        even.append(num)
print(even)

[4, 678, 34, 52, 98, 12, 32]

In [121]:
# now with

In [122]:
numbers = [23,4,523,678,34,52,87,98,12,32,45,67]

In [123]:
[num for num in numbers if num%2 == 0]

[4, 678, 34, 52, 98, 12, 32]

In [ ]:
#Same output

## Task - 5

In [124]:
nums = [1, 2, 3]
result = list(map(lambda x: x * 2, nums))

In [125]:
result

[2, 4, 6]

In [130]:
nums = [1, 2, 3]
result = list(map(lambda x: x % 2, nums))

In [131]:
result

[1, 0, 1]

In [132]:
words = ['apple', 'pear']
result = list(map(str.upper, words))

In [133]:
result

['APPLE', 'PEAR']

#### Filter

In [136]:
nums = [1, 2, 3, 4]
result = list(filter(lambda x: x % 2 == 0, nums))

In [137]:
result

[2, 4]

In [139]:
words = ['cat', 'elephant', 'dog']
animal = list(filter(lambda w: len(w) > 3, words))

In [140]:
animal

['elephant']

#### Reduce

In [149]:
 from functools import reduce
nums = [1, 2, 3, 4]
result = reduce(lambda x, y: x + y, nums) 
# to sum the list

In [150]:
result

10

In [151]:
nums = [5, 12, 8, 2]
result = reduce(lambda a, b: a if a > b else b, nums)

In [152]:
result

12

#### --- The End ----